export const data = [
    
       {id: 1, productInfo:"2 Classic Collection Garage Door", cartName:"2 Entry Door Johnson_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Manoj Bajpayee",
        expiry:6 },
       {id: 2, productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry:4},
       {id: 3, productInfo:"Canyon Ridge® Collection Ultra-Grain® Series with Intellicore®", cartName:"Michigan_Classic14209123",
        shhipingPoint:"ABC Plant",
        createdBy:"Steve Benneth...",
        expiry:90},
       {id: 4, productInfo:"Hardware Special - Stock. W4.HB.8.0.7.0.None.Sol - WH.9.G.2J.B..S", cartName:"JohnDavid_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Manhatton Cree...",
        expiry:90, status: "new"},
       {id: 5, productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry:5},
        {id: 6, productInfo:"2 Classic Collection Garage Door", cartName:"2 Entry Door Johnson_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Manoj Bajpayee",
        expiry: 8},
       {id: 7, productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry:6},
       {id: 8, productInfo:"Canyon Ridge® Collection Ultra-Grain® Series with Intellicore®", cartName:"Michigan_Classic14209123",
        shhipingPoint:"ABC Plant",
        createdBy:"Steve Benneth...",
        expiry: 90},
       {id: 9, productInfo:"Hardware Special - Stock. W4.HB.8.0.7.0.None.Sol - WH.9.G.2J.B..S", cartName:"JohnDavid_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Manhatton Cree...",
        expiry:90},
        {id: 10, productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry: 5},
       {id: 11, productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry:6},
        {id: 12, productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry: 3}
        
];