export const data = [
    
       { productInfo:"2 Classic Collection Garage Door", cartName:"2 Entry Door Johnson_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Manoj Bajpayee",
        expiry:6 },
       { productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry:4},
       { productInfo:"Canyon Ridge® Collection Ultra-Grain® Series with Intellicore®", cartName:"Michigan_Classic14209123",
        shhipingPoint:"ABC Plant",
        createdBy:"Steve Benneth...",
        expiry:90},
       { productInfo:"Hardware Special - Stock. W4.HB.8.0.7.0.None.Sol - WH.9.G.2J.B..S", cartName:"JohnDavid_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Manhatton Cree...",
        expiry:90, status: "new"},
       { productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry:5},
        { productInfo:"2 Classic Collection Garage Door", cartName:"2 Entry Door Johnson_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Manoj Bajpayee",
        expiry: 8},
       { productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry:6},
       { productInfo:"Canyon Ridge® Collection Ultra-Grain® Series with Intellicore®", cartName:"Michigan_Classic14209123",
        shhipingPoint:"ABC Plant",
        createdBy:"Steve Benneth...",
        expiry: 90},
       { productInfo:"Hardware Special - Stock. W4.HB.8.0.7.0.None.Sol - WH.9.G.2J.B..S", cartName:"JohnDavid_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Manhatton Cree...",
        expiry:90},
        { productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry: 5},
       { productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry:6},
        { productInfo:"10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE", cartName:"Carter_Classic14209123",
        shhipingPoint:"Russia Plant",
        createdBy:"Steve Benneth...",
        expiry: 3}
        
];